### ISSUE TITLE
Can`t resolve #app in a nuxt project since v3.1.1

### ISSUE THREAD

**Issue by apss-pohl** [import-js/eslint-import-resolver-typescript#117]
Hi,
since v3 my nuxt3 projects breaks:
`error    Unable to resolve path to module '#app'                import/no-unresolved`
Also the IDE complains. If i go back to v2.7.0 everything works as expected.

The tsconfig gets extended with the generated tsconfig which has the path definition for  #app
tsconfig.json
`  "extends": "./.nuxt/tsconfig.json",`

/.nuxt/tsconfig.json"
```
"paths": {
      "#app/*": [
        "../../node_modules/nuxt/dist/app/*"
      ],
}
```
.eslintrc
```
 import/resolver:
    typescript:
      project: 
        - ./tsconfig.json
        - apps/*/tsconfig.json
        - apps/render/.nuxt/tsconfig.json
```
I hope this enough information provided. Let me know if i can help.
Thank you!
